### PR TITLE
Fix for #259: Always prepare remote platforms

### LINKED ISSUE #259: Plugins not working on full build, fine after incremental build
Cordova App, deployed from Visual Studio 2015 to a Mac build server. Cordova 5.4.1
The first build always fails. The ondeviceReady() function is called, but all plugins like window.StatusBar are null.
When I then deploy again, an incremental build is generated, and the error is gone.

This happens every time. Is there anything I can check?

### PR DESCRIPTION
**Pull request by guillaumejenkins**
The newer Cordova versions have stopped implicitly calling "prepare" when a platform is added. We must now always manually prepare platforms, whether we add the platform or not.

Fixes #259.

### CODE REVIEW

File: src/taco-remote-lib/common/builder.ts [hunk 1]
```diff
@@ -162,7 +153,7 @@ class Builder {
         if (xmlVersion) {
             mustReAddPromise = this.getCurrentPlatformVersion().then((currentVersion: string) => {
                 if (!semver.satisfies(currentVersion, xmlVersion)) {
```
Comment (MSLaguana) [inline src/taco-remote-lib/common/builder.ts]: It looks like this section is redundant now since we always invoke prepare rather than conditionally

Comment (MSLaguana) [inline src/taco-remote-lib/common/builder.ts]: Oh nevermind This is for re-adding the platform, not whether we need to prepare. Disregard.

File: src/taco-remote-lib/common/builder.ts [hunk 2]
```diff
@@ -132,28 +132,19 @@ class Builder {
             fs.mkdirSync("platforms");
```
Comment (MSLaguana) [inline src/taco-remote-lib/common/builder.ts]: Might be worth changing this function name to `addAndPreparePlatform` to be more accurate.

**Comment by MSLaguana** [comment]
Looks good to me

**Comment by nisheetjain** [comment]
:+1:
