### PR TITLE
Only modify the correct plist file

### LINKED ISSUE #253: [iOS] Livereload not working
I get this error when trying to use --livereload with ios.
```
[BS] Watching files...
TACO Livereload Error occured: - TypeError: Cannot read property 'nodeName' of null
TACO Livereload Error occured: - TypeError: Cannot read property 'nodeName' of null
ERROR running one or more of the platforms: TypeError: Cannot read property 'nodeName' of null
```
heres my start command:
```
taco run ios --device --livereload
```

### PR DESCRIPTION
**Pull request by joshuaskelton**
Correcting the globstar match.

Fixes #253

### CODE REVIEW

**Comment by nisheetjain** [comment]
@omefire can you please review this?

File: src/taco-livereload/lib/utils/ATSRemover.js [hunk 1]
```diff
@@ -17,7 +17,8 @@ module.exports = function(projectRoot, platform) {
     var self = this;
     this.Remove = function() {
         var configFolder = path.join(projectRoot, 'platforms', platform, multiPlatforms.getConfigFolder(platform));
-        glob.sync('**/*Info.plist', {
+        // We only want to modify a single plist file, not all of them.
```
Comment (omefire) [inline src/taco-livereload/lib/utils/ATSRemover.js]: While this comment may make sense in the context of this PR/bug fix, it will only confuse anyone else reading the code who doesn't have that context. Please, remove it.

**Comment by omefire** [comment]
LGTM! 
Even though in the future, we might want to be able to have the exact location of ios platform's Info.plist file so that we don't have to do a search. That's probably a bigger undertaking.
